### ISSUE TITLE
三星s7edge上没用啊

### ISSUE THREAD

**Issue by LouisShark** [Marswin/MarsDaemon#36]
我用这个写法直接没用啊 还是需要别的so库啊 还望赐教

**Comment by cddjr** [comment]
作者这个拉活原理是跟系统抢时间，属于然并卵的方案，5.1以上系统在没有系统漏洞的情况下，你还是放弃保活吧，否则掐时间的可靠性太低，甚至可能造成内存、CPU资源的消耗异常。
5.0以下可以用双进程，5.1以下可以利用漏洞再配合双进程保活。

**Comment by LouisShark** [comment]
我现在是使用C中socket的方式进行的保活 好久以前的问题可以关闭了 谢谢回答@cddjr
